<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/deployment/v1/message.proto

namespace Temporal\Api\Deployment\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Used as part of WorkflowExecutionStartedEventAttributes to pass down the AutoUpgrade behavior and source deployment version 
 * to a workflow execution whose parent/previous workflow has an AutoUpgrade behavior.
 *
 * Generated from protobuf message <code>temporal.api.deployment.v1.InheritedAutoUpgradeInfo</code>
 */
class InheritedAutoUpgradeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The source deployment version of the parent/previous workflow.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentVersion source_deployment_version = 1;</code>
     */
    protected $source_deployment_version = null;
    /**
     * The revision number of the source deployment version of the parent/previous workflow.
     *
     * Generated from protobuf field <code>int64 source_deployment_revision_number = 2;</code>
     */
    protected $source_deployment_revision_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Temporal\Api\Deployment\V1\WorkerDeploymentVersion $source_deployment_version
     *           The source deployment version of the parent/previous workflow.
     *     @type int|string $source_deployment_revision_number
     *           The revision number of the source deployment version of the parent/previous workflow.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Deployment\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * The source deployment version of the parent/previous workflow.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentVersion source_deployment_version = 1;</code>
     * @return \Temporal\Api\Deployment\V1\WorkerDeploymentVersion|null
     */
    public function getSourceDeploymentVersion()
    {
        return $this->source_deployment_version;
    }

    public function hasSourceDeploymentVersion()
    {
        return isset($this->source_deployment_version);
    }

    public function clearSourceDeploymentVersion()
    {
        unset($this->source_deployment_version);
    }

    /**
     * The source deployment version of the parent/previous workflow.
     *
     * Generated from protobuf field <code>.temporal.api.deployment.v1.WorkerDeploymentVersion source_deployment_version = 1;</code>
     * @param \Temporal\Api\Deployment\V1\WorkerDeploymentVersion $var
     * @return $this
     */
    public function setSourceDeploymentVersion($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Deployment\V1\WorkerDeploymentVersion::class);
        $this->source_deployment_version = $var;

        return $this;
    }

    /**
     * The revision number of the source deployment version of the parent/previous workflow.
     *
     * Generated from protobuf field <code>int64 source_deployment_revision_number = 2;</code>
     * @return int|string
     */
    public function getSourceDeploymentRevisionNumber()
    {
        return $this->source_deployment_revision_number;
    }

    /**
     * The revision number of the source deployment version of the parent/previous workflow.
     *
     * Generated from protobuf field <code>int64 source_deployment_revision_number = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSourceDeploymentRevisionNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->source_deployment_revision_number = $var;

        return $this;
    }

}

