<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/cloud/identity/v1/message.proto

namespace Temporal\Api\Cloud\Identity\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cloud.identity.v1.Access</code>
 */
class Access extends \Google\Protobuf\Internal\Message
{
    /**
     * The account access
     *
     * Generated from protobuf field <code>.temporal.api.cloud.identity.v1.AccountAccess account_access = 1;</code>
     */
    protected $account_access = null;
    /**
     * The map of namespace accesses
     * The key is the namespace name and the value is the access to the namespace
     *
     * Generated from protobuf field <code>map<string, .temporal.api.cloud.identity.v1.NamespaceAccess> namespace_accesses = 2;</code>
     */
    private $namespace_accesses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Temporal\Api\Cloud\Identity\V1\AccountAccess $account_access
     *           The account access
     *     @type array|\Google\Protobuf\Internal\MapField $namespace_accesses
     *           The map of namespace accesses
     *           The key is the namespace name and the value is the access to the namespace
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cloud\Identity\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * The account access
     *
     * Generated from protobuf field <code>.temporal.api.cloud.identity.v1.AccountAccess account_access = 1;</code>
     * @return \Temporal\Api\Cloud\Identity\V1\AccountAccess|null
     */
    public function getAccountAccess()
    {
        return $this->account_access;
    }

    public function hasAccountAccess()
    {
        return isset($this->account_access);
    }

    public function clearAccountAccess()
    {
        unset($this->account_access);
    }

    /**
     * The account access
     *
     * Generated from protobuf field <code>.temporal.api.cloud.identity.v1.AccountAccess account_access = 1;</code>
     * @param \Temporal\Api\Cloud\Identity\V1\AccountAccess $var
     * @return $this
     */
    public function setAccountAccess($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Cloud\Identity\V1\AccountAccess::class);
        $this->account_access = $var;

        return $this;
    }

    /**
     * The map of namespace accesses
     * The key is the namespace name and the value is the access to the namespace
     *
     * Generated from protobuf field <code>map<string, .temporal.api.cloud.identity.v1.NamespaceAccess> namespace_accesses = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getNamespaceAccesses()
    {
        return $this->namespace_accesses;
    }

    /**
     * The map of namespace accesses
     * The key is the namespace name and the value is the access to the namespace
     *
     * Generated from protobuf field <code>map<string, .temporal.api.cloud.identity.v1.NamespaceAccess> namespace_accesses = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setNamespaceAccesses($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Temporal\Api\Cloud\Identity\V1\NamespaceAccess::class);
        $this->namespace_accesses = $arr;

        return $this;
    }

}

