<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/cloud/namespace/v1/message.proto

namespace Temporal\Api\Cloud\PBNamespace\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cloud.namespace.v1.ExportSinkSpec</code>
 */
class ExportSinkSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique name of the export sink, it can't be changed once set.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * A flag indicating whether the export sink is enabled or not.
     *
     * Generated from protobuf field <code>bool enabled = 2;</code>
     */
    protected $enabled = false;
    /**
     * The S3 configuration details when destination_type is S3.
     *
     * Generated from protobuf field <code>.temporal.api.cloud.sink.v1.S3Spec s3 = 3;</code>
     */
    protected $s3 = null;
    /**
     * This is a feature under development. We will allow GCS sink support for GCP Namespaces.
     * The GCS configuration details when destination_type is GCS.
     *
     * Generated from protobuf field <code>.temporal.api.cloud.sink.v1.GCSSpec gcs = 4;</code>
     */
    protected $gcs = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The unique name of the export sink, it can't be changed once set.
     *     @type bool $enabled
     *           A flag indicating whether the export sink is enabled or not.
     *     @type \Temporal\Api\Cloud\Sink\V1\S3Spec $s3
     *           The S3 configuration details when destination_type is S3.
     *     @type \Temporal\Api\Cloud\Sink\V1\GCSSpec $gcs
     *           This is a feature under development. We will allow GCS sink support for GCP Namespaces.
     *           The GCS configuration details when destination_type is GCS.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cloud\PBNamespace\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique name of the export sink, it can't be changed once set.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The unique name of the export sink, it can't be changed once set.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * A flag indicating whether the export sink is enabled or not.
     *
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * A flag indicating whether the export sink is enabled or not.
     *
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * The S3 configuration details when destination_type is S3.
     *
     * Generated from protobuf field <code>.temporal.api.cloud.sink.v1.S3Spec s3 = 3;</code>
     * @return \Temporal\Api\Cloud\Sink\V1\S3Spec|null
     */
    public function getS3()
    {
        return $this->s3;
    }

    public function hasS3()
    {
        return isset($this->s3);
    }

    public function clearS3()
    {
        unset($this->s3);
    }

    /**
     * The S3 configuration details when destination_type is S3.
     *
     * Generated from protobuf field <code>.temporal.api.cloud.sink.v1.S3Spec s3 = 3;</code>
     * @param \Temporal\Api\Cloud\Sink\V1\S3Spec $var
     * @return $this
     */
    public function setS3($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Cloud\Sink\V1\S3Spec::class);
        $this->s3 = $var;

        return $this;
    }

    /**
     * This is a feature under development. We will allow GCS sink support for GCP Namespaces.
     * The GCS configuration details when destination_type is GCS.
     *
     * Generated from protobuf field <code>.temporal.api.cloud.sink.v1.GCSSpec gcs = 4;</code>
     * @return \Temporal\Api\Cloud\Sink\V1\GCSSpec|null
     */
    public function getGcs()
    {
        return $this->gcs;
    }

    public function hasGcs()
    {
        return isset($this->gcs);
    }

    public function clearGcs()
    {
        unset($this->gcs);
    }

    /**
     * This is a feature under development. We will allow GCS sink support for GCP Namespaces.
     * The GCS configuration details when destination_type is GCS.
     *
     * Generated from protobuf field <code>.temporal.api.cloud.sink.v1.GCSSpec gcs = 4;</code>
     * @param \Temporal\Api\Cloud\Sink\V1\GCSSpec $var
     * @return $this
     */
    public function setGcs($var)
    {
        GPBUtil::checkMessage($var, \Temporal\Api\Cloud\Sink\V1\GCSSpec::class);
        $this->gcs = $var;

        return $this;
    }

}

