<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/cloud/namespace/v1/message.proto

namespace Temporal\Api\Cloud\PBNamespace\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>temporal.api.cloud.namespace.v1.HighAvailabilitySpec</code>
 */
class HighAvailabilitySpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Flag to disable managed failover for the namespace.
     *
     * Generated from protobuf field <code>bool disable_managed_failover = 1;</code>
     */
    protected $disable_managed_failover = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $disable_managed_failover
     *           Flag to disable managed failover for the namespace.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Temporal\Api\Cloud\PBNamespace\V1\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Flag to disable managed failover for the namespace.
     *
     * Generated from protobuf field <code>bool disable_managed_failover = 1;</code>
     * @return bool
     */
    public function getDisableManagedFailover()
    {
        return $this->disable_managed_failover;
    }

    /**
     * Flag to disable managed failover for the namespace.
     *
     * Generated from protobuf field <code>bool disable_managed_failover = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisableManagedFailover($var)
    {
        GPBUtil::checkBool($var);
        $this->disable_managed_failover = $var;

        return $this;
    }

}

